# sudo: required
language:
  - generic

services:
  - docker

before_install:
  - docker build -t elvenvdk/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true elvenvdk/frontend npm run test -- --coverage
